version: "3"

services:
  app:
    container_name: fastapi-tortoise-arq-uvicorn
    build: .
    env_file: .env
    depends_on:
      - database
      - redis
    ports:
      - 80:80

  worker:
    container_name: fastapi-tortoise-arq-uvicorn-worker
    build: .
    depends_on:
      - database
      - redis
    env_file: .env
    command: arq app.worker.WorkerSettings

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  database:
    image: "postgres:latest"
    container_name: database
    restart: always
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
