version: "3"

services:
  app:
    container_name: fastapi-gino-arq-uvicorn
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_IP=cache
      - REDIS_PORT=6379
      - DB_URL=postgres://postgres:postgres@database:5432/postgres
    depends_on:
      - database
      - redis

  worker:
    container_name: fastapi-gino-arq-uvicorn-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - database
      - redis
    environment:
      - ARQ_BACKGROUND_FUNCTIONS=app.tasks.scrap.scrap_hackernews
      - REDIS_IP=cache
      - REDIS_PORT=6379
      - DB_URL=postgres://postgres:postgres@database:5432/postgres
    env_file: .env

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  database:
    image: "postgres:latest"
    container_name: database
    restart: always
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
